spring:
  application:
    name: api-gateway


server:
  port: 8070


springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/api-docs

logstash:
  url: localhost:4560

log:
  path: logs


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 2000
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 5000