spring:
  application:
    name: consumer-demo
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8083


springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/api-docs

logstash:
  url: localhost:4560

log:
  path: logs


# ribbon默认配置
#ribbon.ConnectTimeout=250
#ribbon.ReadTimeout=1000
#ribbon.OkToRetryOnAllOperations=true
#ribbon.MaxAutoRetriesNextServer=2
#ribbon.MaxAutoRetries=0

# feign日志配置, 指定某个service的日志级别
logging.level.com.test.cloud.client.UserClient: DEBUG

# ribbon全局默认连接和等待时间
ribbon.ConnectTimeout: 1
ribbon.ReadTimeout: 10000

# ribbon指定service的连接和等待时间，注意service的名称要和在FeignClient注解里标注的内容一致, 要大写都大写，要小写都小写
provider-demo.ribbon.ConnectTimeout: 1
provider-demo.ribbon.ReadTimeout: 1

# feign全局开启hystrix支持,默认false
feign.hystrix.enabled: true
# hystrix全局默认超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
# hystrix指定request的单独设置超时时间， commandkey的组成为ClientClassName#methodName(ParamTypeClassName..)
hystrix.command.UserClient#list().execution.isolation.thread.timeoutInMilliseconds: 5000